name: Publish Package to npmjs
# on:
#   push:
#     tags:
#       - 'v*'
# trigger
on:
  push:
    branches:
     - master
  pull_request:
    branches:
      - master
    # Execute the action on closed (merged) PR.
    types:
      [closed]
permissions:
  contents: write
jobs:
  build:
    if: github.repository == 'CitizenKonnect/gluegunplus'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install jq
        run: sudo apt-get install jq

      - name: Extract version from package.json
        id: extract_version
        run: echo ::set-output name=version::$(jq -r .version package.json)
      
      - name: Configure Git Identity
        run: |
          git config --global user.email "surgbc@gmail.com"
          git config --global user.name "Brian Onang'o"

      - name: Create Git Tag
        run: git tag -a v${{ steps.extract_version.outputs.version }} -m "Release version v${{ steps.extract_version.outputs.version }}"

      - name: Push Git Tag
        run: git push origin v${{ steps.extract_version.outputs.version }}
