name: Publish Package to npmjs
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: npm publish
        run: |
          TAG=$(echo "${{ github.ref }}" | cut -d '/' -f 3) # Extract tag from github.ref
          npm publish --tag "${TAG}" --access public # Publish with the extracted tag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
